### ISSUE TITLE
Feature Request: Ability to control dot shape

### ISSUE THREAD

**Issue by OR13** [hellobloom/qr-react#12]
Rounded dots look awesome with your logo, but not no much with ours, would be cool to be able to make them squares like they are in vanilla QR Codes.

**Comment by JaceHensley** [comment]
Yeah I've been thinking of adding eyeRenderer and dotRenderer props, then you'd be able to fully control how the dots and eyes look

**Comment by JaceHensley** [comment]
@OR13 just put up #13 to address this
